import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../sections/NavBar";
import Hero from "../sections/Hero";
import ShowCaseSection from "../sections/ShowCase";
import LogoSection from "@/components/LogoSection";
import FeatureCards from "../sections/FeatureCards";
import ExperienceSection from "../sections/Experience";
import Testimonials from "../sections/Testimonials";
import Contact from "../sections/Contact";
import Footer from "../sections/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <NavBar />
      <Hero />
      <ShowCaseSection />
      <LogoSection />
      <FeatureCards />
      <ExperienceSection />
      {/* <TechStack /> */}
      <Testimonials />
      <Contact />
      <Footer />
      {children}</body>
    </html>
  );
}
